### ISSUE TITLE
Folder '/movies/' is not writable by user 'kah' when adding Radarr root folder

### ISSUE THREAD

**Issue by d1ddle** [imjustleaving/trueNAS#1]
Fresh install of TrueNAS Scale, after trying to add /movies/ as a root folder in Radarr.
Checked that all steps before hand were completed correctly, especially automatically inherit permissions for the datasets.

```
2023-06-21 16:16:53.2|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v4.5.2.7388] FluentValidation.ValidationException: Validation failed: 
 -- Path: Folder '/movies/' is not writable by user 'kah'
   at Radarr.Http.REST.RestController`1.ValidateResource(TResource resource, Boolean skipValidate, Boolean skipSharedValidate) in ./Radarr.Http/REST/RestController.cs:line 119
   at Radarr.Http.REST.RestController`1.OnActionExecuting(ActionExecutingContext context) in ./Radarr.Http/REST/RestController.cs:line 78
   at Microsoft.AspNetCore.Mvc.Controller.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/BufferingMiddleware.cs:line 28
   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/IfModifiedMiddleware.cs:line 41
   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/CacheHeaderMiddleware.cs:line 33
   at Radarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/StartingUpMiddleware.cs:line 38
   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/UrlBaseMiddleware.cs:line 27
   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Radarr.Http/Middleware/VersionMiddleware.cs:line 29
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


2023-06-21 16:16:53.2|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- Path: Folder '/movies/' is not writable by user 'kah'
2023-06-21 16:19:30.7|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.
```
Edit: possible fixes, will try when I have access to my Nas.
https://github.com/linuxserver/docker-radarr/issues/132

**Comment by serversathome-personal** [comment]
i would like to see what the permissions for the dataset look like. chances are the "automatic permissions" misfired and thats why you are having that issue. radarr is running as user 568 apps which is what needs the permission. 

you could do two things, go through the shell and:

1. chmod 777 movies to open up permissions for everyone
2. chown apps movies && chgrp apps movies

**Comment by d1ddle** [comment]
Hey, unfortunately after running all 3 commands as root for "/mnt/tank/data" (I use a single dataset optimal for hardlinks), I still get the same error.
I followed the sections [here](https://trash-guides.info/Hardlinks/How-to-setup-for/Docker/#folder-structure) when creating my dataset and before executing any chmod/chown commands, and also executed the [permissions commands](https://trash-guides.info/Hardlinks/How-to-setup-for/Docker/#permissions) on that page using the apps user but I still get the error :(
Just to reiterate this happens when I try to add any root folder to radarr

**Comment by serversathome-personal** [comment]
![image](https://github.com/imjustleaving/trueNAS/assets/109609649/554fed8f-cdbd-4736-9552-eba77e0304d9)
is this what your userID/groupID looks like when you click the 3 vertical dots in the radarr card and click "Edit"?

**Comment by d1ddle** [comment]
Fixed, finally, by ticking "Apply recursively" "to subfolders and subdatasets" in dataset permission settings in TrueNas Scale.
https://www.truenas.com/community/threads/truenas-scale-permission.98480/
